/* eslint-disable no-dupe-keys */
const ActionTypes = {
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_PROGRESS: 'CREATE_CUSTOMER_PROGRESS',
    CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_PROGRESS: 'GET_USER_PROGRESS',
    GET_USER_FAILED: 'GET_USER_FAILED',

    GET_USER_SINGUP_SUCCESS: 'GET_USER_SINGUP_SUCCESS',
    GET_USER_SINGUP_PROGRESS: 'GET_USER_SINGUP_PROGRESS',


    /////*****GET PAYMENT USER DATA */

    GET_USER_PAYMENT_PROGRESS: "GET_USER_PAYMENT_PROGRESS",
    GET_USER_PAYMENT_SUCCESS: "GET_USER_PAYMENT_SUCCESS",

    ///*****///*****GET USER MESSAGE */ */

    GET_USER_MESAAGE_SUCCESS: "GET_USER_MESAAGE_SUCCESS",
    GET_USER_MESSAGE_PROGRESS: 'GET_USER_MESSAGE_PROGRESS',


    ///*****///*****GET USER PAYMENTS */ */

    GET_USER_PAYMENT_PROGRESSs: "GET_USER_PAYMENT_PROGRESSs",
    GET_USER_PAYMENT_SUCCESSs: "GET_USER_PAYMENT_SUCCESSs",

    NOTIFICATION_PROGRESS: "NOTIFICATION_PROGRESS",
    NOTIFICATION_SUCCEED: 'NOTIFICATION_SUCCEED',


    GET_USER_OBJECT: "GET_USER_OBJECT",


    /////////**********Get UTILITY payment */
    GET_UTILITY_PAYMENT_PROGRESS: "GET_UTILITY_PAYMENT_PROGRESS",
    GET_UTILITY_PAYMENT_SUCCESS: "GET_UTILITY_PAYMENT_SUCCESS",



    //////////////Get utility bills
    GET_Bill_PROGRESS: "GET_Bill_PROGRESS",
    GET_Bill_SUCCESS: "GET_Bill_SUCCESS",


    GET_USER_PAYMENT_OBJECT:"GET_USER_PAYMENT_OBJECT"

};






export default ActionTypes;